### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Hetols** [VermiIIi0n/fuckZHS#4]
**描述问题**
获取信息错误

**如何复现**
您遇到问题前进行了什么操作:
命令行登录

**您的操作系统和所使用的本代码版本**
 - OS: Ubuntu 21.04
 - Version latest

**错误日志**
请附上您认为重要的日志，不能判断的话请附上完整日志.
Login Successful

Traceback (most recent call last):
  File "/home/hetols/Python/Project/fuckZHS/main.py", line 122, in <module>
    fucker.fuckWhatever()
  File "/home/hetols/Python/Project/fuckZHS/fucker.py", line 160, in fuckWhatever
    zhidao_ids = [c.secret for c in self.getZhidaoList()]
TypeError: 'NoneType' object is not iterable

**Comment by VermiIIi0n** [comment]
已更新, 麻烦看看修复了没, 是个很傻的小问题
