### ISSUE TITLE
[BUG]Python小白求教

### ISSUE THREAD

**Issue by EnjoyRising** [VermiIIi0n/fuckZHS#46]
Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\fuckZHS-2.3.8\main.py", line 7, in <module>
    from fucker import Fucker
  File "C:\Users\xxxx\Desktop\fuckZHS-2.3.8\fucker.py", line 4, in <module>
    from utils import progressBar, HMS, wipeLine
  File "C:\Users\xxxx\Desktop\fuckZHS-2.3.8\utils.py", line 91, in <module>
    length = (os.get_terminal_size().columns-4), fill = '#'):
OSError: [WinError 6] 句柄无效。

**Comment by Dongxiaohaoo** [comment]
不要在Pycharm里面运行 直接在cmd窗口 python main.py就行了,
如果非要在Pycharm中运行调试, 可以删除这个方法, import的地方也删掉就行了

**Comment by EnjoyRising** [comment]
我去！一次成
