### ISSUE TITLE
[BUG]运行失败

### ISSUE THREAD

**Issue by Hyx0907** [VermiIIi0n/fuckZHS#50]
**描述问题**
用命令提示符运行，显示如下
C:\Windows\system32>py "E:\fuckZHS-master\main.py"
Traceback (most recent call last):
  File "E:\fuckZHS-master\main.py", line 7, in <module>
    from fucker import Fucker
  File "E:\fuckZHS-master\fucker.py", line 4, in <module>
    from utils import progressBar, HMS, wipeLine
  File "E:\fuckZHS-master\utils.py", line 6, in <module>
    from PIL import Image, ImageOps
ModuleNotFoundError: No module named 'PIL'

然后尝试用pip安装这个叫PIL的模块，pip提示没有找到。

**您的操作系统和所使用的本代码版本**
 - OS: Windows 11
 - Version: 2.3.8

**Comment by VermiIIi0n** [comment]
你没装依赖，再看看说明吧

**Comment by VermiIIi0n** [comment]
依赖装完了报的什么错呢

**Comment by Hyx0907** [comment]
还是上面那个ModuleNotFoundError: No module named 'PIL'
