### ISSUE TITLE
[BUG] 刷课 报错 句柄无效

### ISSUE THREAD

**Issue by imyuanli** [VermiIIi0n/fuckZHS#89]
**描述问题**
请详细清晰地描述问题、
刷课报错

**如何复现**
您遇到问题前进行了什么操作:
1. 输入配置，然后直接运行main文件，扫码登录
2. 登录后出现cookie文件，运行fetch命令出现execution文件
3. 再次运行项目，扫码登录后，刷课报错

**截图**
![image](https://github.com/VermiIIi0n/fuckZHS/assets/75649798/86aed4bc-dda1-4e5b-9b71-5aa147ccf140)

**您的操作系统和所使用的本代码版本**
 - OS: [e.g. stupid Windows]  windows11
 - Version: [e.g. 2.0.2]  1.3.0

**错误日志**
请附上您认为重要的日志，不能判断的话请附上完整日志.
最好有 DEBUG 级别日志(使用参数 `-d` 或在配置文件中更改日志等级)

2024-03-28 10:24:31,856:  [WinError 6] 句柄无效。
Traceback (most recent call last):
  File "D:\fuckZHS\main.py", line 223, in <module>
    fucker.fuckCourse(course_id=c)
  File "D:\fuckZHS\fucker.py", line 300, in fuckCourse
    self.fuckZhidaoCourse(course_id, tree_view=tree_view) # it's a recruitAndCourseId
  File "D:\fuckZHS\fucker.py", line 426, in fuckZhidaoCourse
    w_lim = os.get_terminal_size().columns-1 # width limit for terminal output
OSError: [WinError 6] 句柄无效。
2024-03-28 10:24:33,274:  [WinError 6] 句柄无效。
Traceback (most recent call last):
  File "D:\fuckZHS\main.py", line 223, in <module>
    fucker.fuckCourse(course_id=c)
  File "D:\fuckZHS\fucker.py", line 300, in fuckCourse
    self.fuckZhidaoCourse(course_id, tree_view=tree_view) # it's a recruitAndCourseId
  File "D:\fuckZHS\fucker.py", line 426, in fuckZhidaoCourse
    w_lim = os.get_terminal_size().columns-1 # width limit for terminal output
OSError: [WinError 6] 句柄无效。
2024-03-28 10:24:34,441:  [WinError 6] 句柄无效。
Traceback (most recent call last):
  File "D:\fuckZHS\main.py", line 223, in <module>
    fucker.fuckCourse(course_id=c)
  File "D:\fuckZHS\fucker.py", line 300, in fuckCourse
    self.fuckZhidaoCourse(course_id, tree_view=tree_view) # it's a recruitAndCourseId
  File "D:\fuckZHS\fucker.py", line 426, in fuckZhidaoCourse
    w_lim = os.get_terminal_size().columns-1 # width limit for terminal output
OSError: [WinError 6] 句柄无效。
2024-03-28 10:24:35,585:  [WinError 6] 句柄无效。
Traceback (most recent call last):
  File "D:\fuckZHS\main.py", line 223, in <module>
    fucker.fuckCourse(course_id=c)
  File "D:\fuckZHS\fucker.py", line 300, in fuckCourse
    self.fuckZhidaoCourse(course_id, tree_view=tree_view) # it's a recruitAndCourseId
  File "D:\fuckZHS\fucker.py", line 426, in fuckZhidaoCourse
    w_lim = os.get_terminal_size().columns-1 # width limit for terminal output
OSError: [WinError 6] 句柄无效。
2024-03-28 10:24:36,948:  [WinError 6] 句柄无效。
Traceback (most recent call last):
  File "D:\fuckZHS\main.py", line 223, in <module>
    fucker.fuckCourse(course_id=c)
  File "D:\fuckZHS\fucker.py", line 300, in fuckCourse
    self.fuckZhidaoCourse(course_id, tree_view=tree_view) # it's a recruitAndCourseId
  File "D:\fuckZHS\fucker.py", line 426, in fuckZhidaoCourse
    w_lim = os.get_terminal_size().columns-1 # width limit for terminal output
OSError: [WinError 6] 句柄无效。
2024-03-28 10:24:36,949:  [WinError 6] 句柄无效。
Traceback (most recent call last):
  File "D:\fuckZHS\main.py", line 223, in <module>
    fucker.fuckCourse(course_id=c)
  File "D:\fuckZHS\fucker.py", line 300, in fuckCourse
    self.fuckZhidaoCourse(course_id, tree_view=tree_view) # it's a recruitAndCourseId
  File "D:\fuckZHS\fucker.py", line 426, in fuckZhidaoCourse
    w_lim = os.get_terminal_size().columns-1 # width limit for terminal output
OSError: [WinError 6] 句柄无效。

**Comment by imyuanli** [comment]
确实看了 #25 换成vscode就没这个问题了

**Comment by imyuanli** [comment]
![image](https://github.com/VermiIIi0n/fuckZHS/assets/75649798/628a7b61-8d79-4d92-9564-403c97de5137)
但是我还有个问题啊，为啥跑着跑着上面就不动了

**Comment by VermiIIi0n** [comment]
啊，这个是遇到人机验证了，一次不宜刷太长时间，20分钟就好。人机验证需要网页登陆过一下。
